// Code generated by goctl. DO NOT EDIT.
// Source: template.proto

package server

import (
	"context"

	"github.com/ninekiss/go-zero-demo/quickstartmicro/template/internal/logic/template"
	"github.com/ninekiss/go-zero-demo/quickstartmicro/template/internal/svc"
	"github.com/ninekiss/go-zero-demo/quickstartmicro/template/template"
)

type TemplateServer struct {
	svcCtx *svc.ServiceContext
	template.UnimplementedTemplateServer
}

func NewTemplateServer(svcCtx *svc.ServiceContext) *TemplateServer {
	return &TemplateServer{
		svcCtx: svcCtx,
	}
}

func (s *TemplateServer) Ping(ctx context.Context, in *template.Request) (*template.Response, error) {
	l := templatelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
