// Code generated by goctl. DO NOT EDIT.
// Source: template.proto

package template

import (
	"context"

	"github.com/ninekiss/go-zero-demo/quickstartmicro/template/template"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = template.Request
	Response = template.Response

	Template interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTemplate struct {
		cli zrpc.Client
	}
)

func NewTemplate(cli zrpc.Client) Template {
	return &defaultTemplate{
		cli: cli,
	}
}

func (m *defaultTemplate) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := template.NewTemplateClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
